# Generated by Django 5.1.3 on 2025-07-05 04:11

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
